# Generated by Django 3.1.7 on 2021-10-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='bar_lenght',
            new_name='bar_length',
        ),
    ]
