# Generated by Django 3.1.7 on 2021-10-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211008_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='photo',
        ),
    ]
