# Generated by Django 3.1.7 on 2021-10-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_artist_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='tone',
            new_name='band_tone',
        ),
        migrations.AddField(
            model_name='music',
            name='original_tone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
